<center><h2>Form configuration</h2></center>

<?php
$attr=null;

if(isset($_POST['elementId']) )
{
	//echo 'Root: '.$_SESSION['rootElement'].'<br/>';
	
	//echo 'Element to change: '.$_POST['elementId'].'<br/>';
	$attr=$_SESSION['elementList'][$_POST['elementId']]['attributes'];
	
	//echo 'Former element = ';
	if(isset($_POST['unbounded']) && $_POST['unbounded']=="on") $_POST['max']="unbounded";
	
	/*print_r($attr);
	echo '<br/>';
	print_r($_POST);
	
	echo '<br/>';*/
	
	if(isset($_POST['min']))
	{
		if((isset($attr['MINOCCURS']) && $_POST['min']!=$attr['MINOCCURS']) || (!isset($attr['MINOCCURS']) && $_POST['min']!=1))
		{
			if($_POST['min']==1)
			{
				//echo 'Min needs to be removed<br/>';
				unset($attr['MINOCCURS']);
				
			}
			else
			{
				//echo 'Min needs to be changed<br/>';
				$attr['MINOCCURS'] = $_POST['min'];
			}
		}
		else
		{
			//echo 'Min does not need to be changed<br/>';
		}
	}
	
	if(isset($_POST['max']))
	{
		if((isset($attr['MAXOCCURS']) && $_POST['max']!=$attr['MAXOCCURS']) || (!isset($attr['MAXOCCURS']) && $_POST['max']!=1))
		{
			if($_POST['max']==1)
			{
				//echo 'Max needs to be removed<br/>';
				unset($attr['MAXOCCURS']);
			}
			else
			{
				//echo 'Max needs to be changed<br/>';
				$attr['MAXOCCURS'] = $_POST['max'];
				
			}
		}
		else
		{
			//echo 'Max does not need to be changed<br/>';
		}
	}
	
	if(isset($_POST['type']))
	{
		switch ($_POST['type'])
		{
			// XXX Use global variables (namespace, etc.)
			case 'str':
				$_POST['type']="xsd:string";
				break;
			case 'int':
				$_POST['type']="xsd:integer";
				break;
			case 'dbl':
				$_POST['type']="xsd:double";
				break;
			default:
				break;
			
		}
		
		if(startsWith($attr['TYPE'], "xsd:"))
		{
			if($attr['TYPE']!=$_POST['type'])
			{
				//echo 'Type needs to be changed<br/>';
				$attr['TYPE'] = $_POST['type'];
			}
			else
			{
				//echo 'Type does not need to be changed<br/>';
			}
		}		
	}
	
	if(isset($_POST['ai']) && $_POST['ai']=="on" && !(isset($attr['AI']) && $attr['AI']=="on"))
	{
		//echo "Set autogenerated on<br/>";
		$attr = $attr + array('AI' => 'on');
	}
	else if((!isset($_POST['ai']) || $_POST['ai']!="on") && isset($attr['AI']) && $attr['AI']=="on")
	{
		//echo "Set autogenerated off<br/>";
		unset($attr['AI']);
	}
	
	$_SESSION['elementList'][$_POST['elementId']]['attributes'] = $attr;
	
	/*print_r($attr);
	echo '<br/>';
	
	echo '<hr/>';*/
	
}


if(isset($_SESSION['elementList']))
{
	//echo 'Element list is set<br/>';
}

/*if(isset($_GET['debug']))
{
	echo 'DEBUG : ON<br/>';
	echo '-------<br/>';
}*/

$start = (float) array_sum(explode(' ',microtime()));

$xsd = "resources/files/mgiml_a.xsd";
//$xsd = "files/mgiml_light.xsd";
//$xsd = "resources/files/mgiml_ultra_light.xsd";

// We begin to parse the file
// TODO Could we use ajax to do that ?
$xsd_parser = new XsdParser($xsd);

if(isset($attr) && $attr!=null)
{
	$xsd_parser->setElementList($_SESSION['elementList']);
	$xsd_parser->setRoot($_SESSION['rootElement']);
	$xsd_parser->setNamespace($_SESSION['namespace']);
	
	$xsd_parser->displayForm();
}
else
{
	$xsd_parser->buildForm();
}
?>
<input type="button" class="button" id="tostep2" value="Build the form" />
<?php 
/*echo '<hr/>'; XXX DEBUG
print_r($xsd_parser->getElementList());*/ 


$_SESSION['elementList']=$xsd_parser->getElementList();
$_SESSION['rootElement']=$xsd_parser->getRoot();
$_SESSION['namespace']=$xsd_parser->getNamespace();

$end = (float) array_sum(explode(' ',microtime()));

echo '<hr/>';
echo "Processing time: <b>".sprintf("%.4f", ($end-$start))."</b> seconds<br/>";
echo "Allocating memory: <b>".memory_get_usage().'</b> bytes';

?>

<div id="edition_popup" class="divModalDialog">
<div>
	<p class="popup cancelButton">
		<a href="#"> <img src="resources/close.png" width="20px"
			height="20px" />
		</a>
	</p>
	<p class="popup title" id="popup_title"></p>
	
	<form action="?step=1" method="post">
	<p>
		Min: <input type="number" min="0" value="1" id="min" name="min"/><br />
		Max unbounded? <input type="checkbox" id="unbounded" name="unbounded" onclick="changeEditionStatus('max')"/><br />
		Max: <input type="number" min="0" value="1" id="max" name="max"/><br />
		<!--Editable? <input type="checkbox" id="editable" name="editable" onclick="changeEditionStatus('type')"/><br /-->
		Type: 
		<select id="type" name="type" id="type">
			<option value="">Select type...</option>
			<option value="int">Integer</option>
			<option value="dbl">Double</option>
			<option value="str">String</option>
		</select><br /> 
		Auto-generate? <input type="checkbox" id="ai" name="ai"/><br />
		<input type="hidden" id="elementId" name="elementId" value=""/>
		
		<input type="button" value="Cancel" onclick="window.location='#'"/>
		<input type="submit" value="Validate" onclick="checkForm()"/>
	</p>
	</form>
</div>
</div>